#NumPy

*How to get the specific array from the many array*

**Array indexing and slicing**

Indexing refers to accessing a specific element of an array by its position or index within the array. array[2].
Slicing, refers to extracting a portion of an array, is done by specifying a range of indices. slice [1:4].

In [124]:
from numpy import *
arr=array([
    [[13,14,15,17],
     [11,10,19,16]],        #[3,2,4] shape

    [[20,24,26,28],
     [20,29,27,22]],   #[1:2,0:,2:] this gives 26,28,27,22
    
    [[33,37,38,31],
     [49,46,43,41]]
    ])

In [125]:
arr.shape   

(3, 2, 4)

In [126]:
#single element
#indexing starts from 0 position
arr[1, 1,2]

27

In [127]:
#subarray using ranges
arr[1:]

array([[[20, 24, 26, 28],
        [20, 29, 27, 22]],

       [[33, 37, 38, 31],
        [49, 46, 43, 41]]])

In [128]:
arr[1:, 0:1]   #selecting only zero skipping 1st arr

array([[[20, 24, 26, 28]],

       [[33, 37, 38, 31]]])

In [129]:
arr[1:, 0:1, :2]   

array([[[20, 24]],

       [[33, 37]]])

In [130]:
#similarly, lets practice
arr[1:2,0:,2: ]

array([[[26, 28],
        [27, 22]]])

In [131]:
arr    #0:,0,2

array([[[13, 14, 15, 17],
        [11, 10, 19, 16]],

       [[20, 24, 26, 28],
        [20, 29, 27, 22]],

       [[33, 37, 38, 31],
        [49, 46, 43, 41]]])

In [132]:
arr[1:, 1, 3]

array([22, 41])

In [133]:
arr[1:, 1, :3]

array([[20, 29, 27],
       [49, 46, 43]])

In [134]:
arr[0:,0,2]

array([15, 26, 38])

In [135]:
arr[:2,1]

array([[11, 10, 19, 16],
       [20, 29, 27, 22]])

In [136]:
concatenate((arr),axis=1)

array([[13, 14, 15, 17, 20, 24, 26, 28, 33, 37, 38, 31],
       [11, 10, 19, 16, 20, 29, 27, 22, 49, 46, 43, 41]])