#Numpy

single dimentional array [1,2,3,4]
multiple dimentional array(2d, 3d)
2d=matrix 
2 3 4
4 5 6
6 7 0
doesnot support thats why we need numpy package

In [9]:
#single D array
from numpy import *

x=array([1,2,3]) # want to specify int then x=array([1,2,3], int)
print(x)

[1 2 3]


In [10]:
#array broadcasting
from numpy import *

x=array([1,2,3])
y=array([3,4,5])
z=x+y     #adding two array
print(z)

[4 6 8]


In [11]:
#flatten()
from numpy import *

x=array([
    
        [1,2,3,4],
        [5,6,7,8]
        
        ]) 
y=x.flatten()   #flattern combines array in single d form
print(y)

[1 2 3 4 5 6 7 8]


In [12]:
#reshape(rows, column)
from numpy import *

x=array([
    
        [1,2,3,4],
        [5,6,7,8]
        
        ]) 
z=x.reshape(2,4) #gives the shape of 4 column, 2 rows matrix(1D to 2D)
print(z)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
#matrix
from numpy import *

x=array([
    
        [1,2,3,4],
        [5,6,7,8]
        
        ]) 
m=matrix(x)   #matrix: 2d array into matrix,
print(m)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
#matrix('rows: rows')
from numpy import *

n=matrix( ' 1 2 3 4 ; 5 6 7 8 ; 2 3 4 0' )
print(n)     #give the output of 3x4 matrix directly, without writing array

[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 0]]


In [15]:
#min, max
from numpy import *

n=matrix( ' 1 2 3 4 ; 5 6 7 8 ; 2 13 4 0' )

print(n)
print(f'Min value: {n.min()}')
print(f'Max value: {n.max()}') 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 2 13  4  0]]
Min value: 0
Max value: 13


In [16]:
from numpy import *

m1=matrix('1 2 3 ; 3 4 5 ; 6 7 8 ')
m2=matrix('1 0 0 ; 0 1 0 ; 0 0 1 ')

m=m1+m2      #addition
print(m)

m3=m1*m2     #multiplication
print('\n',m3)

[[2 2 3]
 [3 5 5]
 [6 7 9]]

 [[1 2 3]
 [3 4 5]
 [6 7 8]]


commonly used functions in NumPy for creating arrays:
array(), linspace(), logspace(), arange(), zeros(), ones() 

In [17]:
#array
from numpy import *
x=array([2,3,4,5,9])

print(x)

[2 3 4 5 9]


In [18]:
from numpy import *

x=linspace(0,12,5) # three argument:start point,end point,number of points in the array, divides number(0 to 12) equally by 5, 5 is the length of array
print(x)

[ 0.  3.  6.  9. 12.]


In [19]:
#logspace()
from numpy import *

x=logspace(0,200,5)  # creates an array with five logarithmically spaced points between 0 and 200
print(x)

[1.e+000 1.e+050 1.e+100 1.e+150 1.e+200]


In [20]:
#arange()
from numpy import *

x=arange(0,20,2)     # this creates array, where 2 is the equally spaced values within a given interval(0,20)
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [21]:
#print 0 as the output zeros()
from numpy import *

x=zeros(20)  
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
#print 1 as the output ones()
from numpy import *

x=ones(20)  
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
